apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-service
  namespace: argocd
spec:
  destination:
    namespace: counter-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/edgaroviz/first_project
    targetRevision: HEAD
    path: charts/counter_service
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true