apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    {{ .Values.appNape }}
