name: Terraform Infra Deployment

#on:
#  workflow_dispatch

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Initialize Terraform
        run: |
          cd tf
          echo "In dir $(pwd)"
          terraform init

      - name: Validate Terraform
        run: |
          terraform fmt -recursive
          cd tf
          terraform validate
          

      - name: Plan Terraform
        run: |
          cd tf
          terraform plan

      - name: Apply Terraform
        run: |
          cd tf
          terraform apply -auto-approve
      
